spring:
    servlet:
        multipart:
        max-file-size: 10MB
        max-request-size: 10MB
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:tebogodb

server:
    port: 8070